baseURL = "https://blog.sonicgd.ru"
languageCode = "ru-ru"
title = "With no power comes no responsibility"
pygmentsCodeFences = true

theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
publishDir = "docs"

[Params]
  subtitle = "With no power comes no responsibility"
  logo = "logo.png"
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true

[Author]
  name = "SonicGD"
  website = "https://sonicgd.ru"
  googleplus = "+sonicgd" # or xxxxxxxxxxxxxxxxxxxxx
  github = "sonicgd"
  gitlab = "sonicgd"
  twitter = "sonicbw"
  reddit = "sonicgd"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3